"""
In-memory disaster database and data access layer for RESQZONE.
Holds regional sectors, habitations, hazards, safe zones, incidents, rescue requests, and alerts.
Preserves authentic Indian disaster telemetry with Census 2011 demographics.
"""

from typing import Dict, List, Optional, Any, Tuple
import time
import json
import os

class DisasterDatabase:
    def __init__(self):
        self._init_data()

    def _init_data(self):
        # 1. Active Sectors / Geographic Hubs
        self.locations: Dict[str, Dict[str, Any]] = {
            "LOC-HALDIA": {
                "id": "LOC-HALDIA",
                "name": "Haldia",
                "district": "Purba Medinipur",
                "state": "West Bengal",
                "coordinates": [22.0667, 88.0698],
                "riskLevel": "HIGH",
                "hazardNotice": "High tidal surge & coastal estuarine inundation advisory along Hooghly & Haldi river confluence.",
                "pincode": "721604",
            },
            "LOC-SILIGURI": {
                "id": "LOC-SILIGURI",
                "name": "Siliguri",
                "district": "Darjeeling",
                "state": "West Bengal",
                "coordinates": [26.7165, 88.3915],
                "riskLevel": "HIGH",
                "hazardNotice": "High flood risk detected along Mahananda & Teesta river basin (Water level +14%).",
                "pincode": "734001",
            },
            "LOC-JOSHIMATH": {
                "id": "LOC-JOSHIMATH",
                "name": "Joshimath",
                "district": "Chamoli",
                "state": "Uttarakhand",
                "coordinates": [30.5564, 79.5668],
                "riskLevel": "CRITICAL",
                "hazardNotice": "Active land subsidence alert: Sector B slope gradient shifts exceeding 4mm/hr in Sunil Ward.",
                "pincode": "246443",
            },
            "LOC-WAYANAD": {
                "id": "LOC-WAYANAD",
                "name": "Wayanad",
                "district": "Wayanad",
                "state": "Kerala",
                "coordinates": [11.6854, 76.1320],
                "riskLevel": "CRITICAL",
                "hazardNotice": "Debris flow red zone: Chooralmala-Meppadi tea plantation hillslopes saturated past 92%.",
                "pincode": "673577",
            },
            "LOC-MUMBAI": {
                "id": "LOC-MUMBAI",
                "name": "Mumbai",
                "district": "Mumbai Suburban",
                "state": "Maharashtra",
                "coordinates": [19.0760, 72.8777],
                "riskLevel": "HIGH",
                "hazardNotice": "Mithi River water level at 3.9m (critical threshold 4.2m). Kurla-Bandra lowlands inundation warning.",
                "pincode": "400001",
            },
            "LOC-DELHI": {
                "id": "LOC-DELHI",
                "name": "Delhi",
                "district": "Central Delhi",
                "state": "Delhi",
                "coordinates": [28.6139, 77.2090],
                "riskLevel": "MODERATE",
                "hazardNotice": "Yamuna river water level at 205.85m exceeding warning mark. Low-lying floodplain evacuation advisory.",
                "pincode": "110001",
            },
        }

        # 2. Hazard Areas (Polygons and Points)
        self.hazards: List[Dict[str, Any]] = [
            {
                "id": "HZ-001",
                "name": "Alaknanda Flash Flood Surge Corridor",
                "type": "Flash Flood",
                "severity": "CRITICAL",
                "riskScore": 9.2,
                "affectedAreaSqKm": 18.5,
                "affectedPopulation": 14200,
                "affectedHabitationsCount": 6,
                "center": [30.5500, 79.5600],
                "polygonPoints": [
                    [30.5650, 79.5400],
                    [30.5700, 79.5750],
                    [30.5400, 79.5850],
                    [30.5350, 79.5500],
                ],
                "recommendedAction": "Immediate evacuation of riverside habitations. Deploy NDRF 14th Bn water rescue teams.",
                "reportedTime": "12 min ago",
                "description": "Glacial lake outburst drainage pulse elevated river volume by 280%. Embankment revetment eroded.",
                "imageUrl": "https://images.unsplash.com/photo-1547683905-f686c993aae5?auto=format&fit=crop&w=1200&q=80",
            },
            {
                "id": "HZ-002",
                "name": "Sunil Ward Subsidence & Slope Rupture",
                "type": "Landslide",
                "severity": "CRITICAL",
                "riskScore": 8.9,
                "affectedAreaSqKm": 6.8,
                "affectedPopulation": 6800,
                "affectedHabitationsCount": 3,
                "center": [30.5620, 79.5710],
                "polygonPoints": [
                    [30.5700, 79.5600],
                    [30.5750, 79.5800],
                    [30.5550, 79.5820],
                    [30.5500, 79.5630],
                ],
                "recommendedAction": "Mandatory red-tag clearance of residential structures. Restrict heavy vehicle traffic on NH-7.",
                "reportedTime": "28 min ago",
                "description": "Subterranean seepage accelerating toe erosion. Shear crack displacement reached 35mm over 12 hours.",
                "imageUrl": "https://images.unsplash.com/photo-1516214104703-d870798883c5?auto=format&fit=crop&w=1200&q=80",
            },
            {
                "id": "HZ-003",
                "name": "Mahananda River Basin Inundation Zone",
                "type": "Riverine Flood",
                "severity": "HIGH",
                "riskScore": 7.6,
                "affectedAreaSqKm": 22.4,
                "affectedPopulation": 24000,
                "affectedHabitationsCount": 8,
                "center": [26.7200, 88.4000],
                "polygonPoints": [
                    [26.7400, 88.3800],
                    [26.7450, 88.4200],
                    [26.7000, 88.4300],
                    [26.6900, 88.3900],
                ],
                "recommendedAction": "Pre-stage rescue inflatable rafts at Ward 12 ghat. Mobilize relief materials to designated high schools.",
                "reportedTime": "15 min ago",
                "description": "Teesta barrage discharge matching continuous torrential hill catchment precipitation of 145mm.",
                "imageUrl": "https://images.unsplash.com/photo-1547683905-f686c993aae5?auto=format&fit=crop&w=1200&q=80",
            },
            {
                "id": "HZ-004",
                "name": "Hooghly-Haldi Estuary Tidal Surge Red Zone",
                "type": "Flash Flood",
                "severity": "CRITICAL",
                "riskScore": 8.8,
                "affectedAreaSqKm": 24.5,
                "affectedPopulation": 18450,
                "affectedHabitationsCount": 5,
                "center": [22.0520, 88.0850],
                "polygonPoints": [
                    [22.0800, 88.0550],
                    [22.0750, 88.1150],
                    [22.0300, 88.1100],
                    [22.0250, 88.0600],
                ],
                "recommendedAction": "Mandatory evacuation of low-lying estuary settlements within 2.5 km of river embankment.",
                "reportedTime": "8 min ago",
                "description": "Astronomical high tide coinciding with 45 knot coastal gale winds causing severe water backflow into drainage canals.",
                "imageUrl": "https://images.unsplash.com/photo-1547683905-f686c993aae5?auto=format&fit=crop&w=1200&q=80",
            }
        ]

        # 3. Habitations / Settlements (Census 2011 baseline data)
        self.habitations: List[Dict[str, Any]] = [
            {
                "id": "HAB-001",
                "name": "Sunil Ward Upper Ridge",
                "district": "Chamoli",
                "state": "Uttarakhand",
                "subdistrict": "Joshimath",
                "level": "ward",
                "ruralUrban": "Urban",
                "households": 340,
                "population": 1680,
                "malePopulation": 890,
                "femalePopulation": 790,
                "children0_6": 180,
                "elderly60Plus": 220,
                "personsWithDisabilities": 28,
                "coordinates": [30.5645, 79.5690],
                "vulnerabilityLevel": "CRITICAL",
                "primaryThreat": "Subsidence fissure widening and structural shearing",
                "soilSaturationIndex": 88.4,
                "riverProximityMeters": 450,
                "slopeAngleDegrees": 34.5,
                "recommendedAction": "Immediate evacuation to Pipalkoti Safe Enclave via Route Corridor A.",
                "assignedSafeZoneId": "SZ-001",
            },
            {
                "id": "HAB-002",
                "name": "Manohar Bagh Settlement",
                "district": "Chamoli",
                "state": "Uttarakhand",
                "subdistrict": "Joshimath",
                "level": "ward",
                "ruralUrban": "Urban",
                "households": 420,
                "population": 2150,
                "malePopulation": 1130,
                "femalePopulation": 1020,
                "children0_6": 240,
                "elderly60Plus": 290,
                "personsWithDisabilities": 34,
                "coordinates": [30.5590, 79.5650],
                "vulnerabilityLevel": "CRITICAL",
                "primaryThreat": "Ground deformation and retaining wall failure",
                "soilSaturationIndex": 84.2,
                "riverProximityMeters": 680,
                "slopeAngleDegrees": 29.0,
                "recommendedAction": "Priority relocation of elderly and young children to Chamoli District Relief Enclave.",
                "assignedSafeZoneId": "SZ-001",
            },
            {
                "id": "HAB-003",
                "name": "Mahananda Ghat Riverside Basti",
                "district": "Darjeeling",
                "state": "West Bengal",
                "subdistrict": "Siliguri",
                "level": "ward",
                "ruralUrban": "Urban",
                "households": 620,
                "population": 3100,
                "malePopulation": 1620,
                "femalePopulation": 1480,
                "children0_6": 380,
                "elderly60Plus": 310,
                "personsWithDisabilities": 45,
                "coordinates": [26.7190, 88.3980],
                "vulnerabilityLevel": "HIGH",
                "primaryThreat": "Severe river inundation and flash torrent overflow",
                "soilSaturationIndex": 92.1,
                "riverProximityMeters": 80,
                "slopeAngleDegrees": 3.0,
                "recommendedAction": "Transfer to Kanchenjunga Stadium Shelter before high-tide river discharge at 18:00.",
                "assignedSafeZoneId": "SZ-003",
            },
            {
                "id": "HAB-004",
                "name": "Sutahata Ward 3 (Bhabanipur Sluice Settlement)",
                "district": "Purba Medinipur",
                "state": "West Bengal",
                "subdistrict": "Sutahata",
                "level": "town",
                "ruralUrban": "Urban",
                "households": 780,
                "population": 3950,
                "malePopulation": 2040,
                "femalePopulation": 1910,
                "children0_6": 410,
                "elderly60Plus": 460,
                "personsWithDisabilities": 52,
                "coordinates": [22.0950, 88.0400],
                "vulnerabilityLevel": "HIGH",
                "primaryThreat": "Canal sluice backflow inundation and high salinity waterlogging",
                "soilSaturationIndex": 94.5,
                "riverProximityMeters": 120,
                "slopeAngleDegrees": 1.2,
                "recommendedAction": "Relocate residents to Haldia Multi-Purpose Cyclone Shelter Complex.",
                "assignedSafeZoneId": "SZ-004",
            }
        ]

        # 4. Safe Zones / Emergency Relief Enclaves
        self.safe_zones: List[Dict[str, Any]] = [
            {
                "id": "SZ-001",
                "name": "Pipalkoti Regional Safe Zone Enclave",
                "type": "Relief Camp",
                "district": "Chamoli",
                "state": "Uttarakhand",
                "coordinates": [30.4289, 79.4310],
                "safeCapacity": 5000,
                "currentOccupancy": 1320,
                "availableCapacity": 3680,
                "accessibility": "GOOD",
                "hazardExposure": "NONE",
                "distanceKm": 18.2,
                "travelTimeMin": 35,
                "facilities": ["Level-2 Medical Triage", "Clean Water RO Plant", "Generator Backup", "Community Kitchen"],
                "contactPerson": "Col. R. K. Rawat, Camp Commander",
                "contactPhone": "+91 94120 88214",
                "medicalUnitAvailable": True,
                "powerBackup": True,
                "status": "SAFE",
                "imageUrl": "https://images.unsplash.com/photo-1578662996442-48f60103fc96?auto=format&fit=crop&w=800&q=80",
            },
            {
                "id": "SZ-002",
                "name": "Gopeshwar Sports Stadium Emergency Center",
                "type": "Stadium",
                "district": "Chamoli",
                "state": "Uttarakhand",
                "coordinates": [30.4130, 79.3280],
                "safeCapacity": 3800,
                "currentOccupancy": 1240,
                "availableCapacity": 2560,
                "accessibility": "GOOD",
                "hazardExposure": "NONE",
                "distanceKm": 24.5,
                "travelTimeMin": 45,
                "facilities": ["Mobile Trauma Van", "Helipad Staging Field", "Sanitation Blocks", "Sheltered Dormitories"],
                "contactPerson": "Dr. Sunita Negi, Chief Medical Officer",
                "contactPhone": "+91 94111 77302",
                "medicalUnitAvailable": True,
                "powerBackup": True,
                "status": "SAFE",
                "imageUrl": "https://images.unsplash.com/photo-1587825140708-dfaf72ae4b04?auto=format&fit=crop&w=800&q=80",
            },
            {
                "id": "SZ-003",
                "name": "Kanchenjunga Stadium Emergency Relief Complex",
                "type": "Stadium",
                "district": "Darjeeling",
                "state": "West Bengal",
                "coordinates": [26.7150, 88.4280],
                "safeCapacity": 6000,
                "currentOccupancy": 1800,
                "availableCapacity": 4200,
                "accessibility": "GOOD",
                "hazardExposure": "NONE",
                "distanceKm": 4.2,
                "travelTimeMin": 12,
                "facilities": ["Centralized Medical Ward", "Clean Drinking Water Cisterns", "NDRF Base Liaison", "Dry Ration Supply Hub"],
                "contactPerson": "Debjit Mukherjee, Disaster Management Officer",
                "contactPhone": "+91 98320 11942",
                "medicalUnitAvailable": True,
                "powerBackup": True,
                "status": "SAFE",
                "imageUrl": "https://images.unsplash.com/photo-1587825140708-dfaf72ae4b04?auto=format&fit=crop&w=800&q=80",
            },
            {
                "id": "SZ-004",
                "name": "Haldia Multi-Purpose Cyclone Shelter Complex",
                "type": "Relief Camp",
                "district": "Purba Medinipur",
                "state": "West Bengal",
                "coordinates": [22.0720, 88.0610],
                "safeCapacity": 4500,
                "currentOccupancy": 1100,
                "availableCapacity": 3400,
                "accessibility": "GOOD",
                "hazardExposure": "NONE",
                "distanceKm": 3.8,
                "travelTimeMin": 10,
                "facilities": ["Elevated Plinth Foundation (6.5m)", "High-Capacity Generators", "Water Treatment Unit", "Child Care Section"],
                "contactPerson": "Subhashis Roy, District Relief Officer",
                "contactPhone": "+91 94340 55198",
                "medicalUnitAvailable": True,
                "powerBackup": True,
                "status": "SAFE",
                "imageUrl": "https://images.unsplash.com/photo-1578662996442-48f60103fc96?auto=format&fit=crop&w=800&q=80",
            },
        ]

        # 5. Multimodal Fleet
        self.fleet: List[Dict[str, Any]] = [
            {
                "id": "FLEET-EB-204",
                "type": "BUS",
                "title": "Emergency Bus",
                "regOrId": "EB-204",
                "capacity": 50,
                "occupied": 42,
                "available": 8,
                "status": "AVAILABLE",
                "pickupLocation": "Joshimath Bus Stand / Transit Point A",
                "etaMin": 8,
                "routeDescription": "Joshimath Ward → Pipalkoti Regional Safe Zone",
                "equipment": ["Oxygen Cylinders", "Stretcher Mount", "GPS Telemetry"],
                "coordinates": [30.5480, 79.5520],
            },
            {
                "id": "FLEET-EV-17",
                "type": "TRAIN",
                "title": "Evacuation Train",
                "regOrId": "EV-17",
                "capacity": 1200,
                "occupied": 860,
                "available": 340,
                "status": "BOARDING",
                "pickupLocation": "Platform 2, Rishikesh-Haridwar Evac Railhead",
                "etaMin": 18,
                "routeDescription": "Haridwar Railhead → Dehradun Relief Terminal",
                "equipment": ["Medical Coach", "Food & Water Pantry", "Onboard Triage"],
                "coordinates": [30.0869, 78.2676],
            },
            {
                "id": "FLEET-RB-09",
                "type": "BOAT",
                "title": "Flood Rescue Boat",
                "regOrId": "RB-09",
                "capacity": 20,
                "occupied": 13,
                "available": 7,
                "status": "AVAILABLE",
                "pickupLocation": "Alaknanda Riverbank Sector 4",
                "etaMin": 6,
                "routeDescription": "Inundated Ghats → Raised Helipad Enclave",
                "equipment": ["Life Jackets (30)", "Submersible Sonar", "First Aid Triage"],
                "coordinates": [30.5420, 79.5580],
            },
            {
                "id": "FLEET-AM-08",
                "type": "AMBULANCE",
                "title": "Emergency Ambulance",
                "regOrId": "AM-08",
                "capacity": 4,
                "occupied": 2,
                "available": 2,
                "status": "EN_ROUTE",
                "pickupLocation": "Joshimath Hospital Emergency Gate",
                "etaMin": 7,
                "routeDescription": "Joshimath Hospital → Helang Trauma Care Unit",
                "equipment": ["Defibrillator Monitor", "Trauma Stretcher", "Advanced Life Support"],
                "coordinates": [30.5510, 79.5580],
            },
        ]

        # 6. Live Incidents
        self.incidents: List[Dict[str, Any]] = [
            {
                "id": "INC-001",
                "title": "Road Subsidence & Fissure Breach on NH-7",
                "type": "Landslide",
                "severity": "CRITICAL",
                "location": "Joshimath Ward 3 Upper Ridge, Chamoli",
                "coordinates": [30.5564, 79.5668],
                "reportedAt": "14 min ago",
                "status": "IN_PROGRESS",
                "description": "45-meter section of road dropped by 1.8 meters. Cracks propagating toward adjacent residential masonry structures.",
                "reportedBy": "NDRF Quick Response Patrol Unit 4",
                "verified": True,
                "casualties": 0,
                "affectedPeople": 450,
                "assignedUnit": "NDRF 14th Battalion Bravo Platoon",
                "imageUrl": "https://images.unsplash.com/photo-1547683905-f686c993aae5?auto=format&fit=crop&w=800&q=80",
            },
            {
                "id": "INC-002",
                "title": "River Inundation at Mahananda Sluice Gate 2",
                "type": "Flash Flood",
                "severity": "HIGH",
                "location": "Mahananda Ghat Riverside, Siliguri",
                "coordinates": [26.7190, 88.3980],
                "reportedAt": "25 min ago",
                "status": "REPORTED",
                "description": "High water levels breaching secondary earthen bund. Approximately 30 households partially surrounded by 0.8m water.",
                "reportedBy": "Citizen Emergency Reporter (P. Sharma)",
                "verified": True,
                "casualties": 0,
                "affectedPeople": 180,
                "assignedUnit": "State Disaster Management Quick Response Squad",
                "imageUrl": "https://images.unsplash.com/photo-1547683905-f686c993aae5?auto=format&fit=crop&w=800&q=80",
            },
        ]

        # 7. Citizen Rescue Requests
        self.rescue_requests: List[Dict[str, Any]] = [
            {
                "id": "REQ-7701",
                "requesterName": "Ramesh Chandra Joshi",
                "contactPhone": "+91 98451 22910",
                "locationName": "Joshimath Ward 4, Near Auli Ropeway Tower 1",
                "coordinates": [30.5520, 79.5610],
                "peopleCount": {"adults": 4, "children": 2, "elderlyOrSpecialCare": 1},
                "urgency": "CRITICAL_IMMEDIATE",
                "emergencyType": "Rescue",
                "message": "Ground underneath verandah collapsed. Retaining wall cracked severely. Senior citizen unable to walk unassisted.",
                "submittedAt": "18 min ago",
                "status": "RESPONSE_DISPATCHED",
                "assignedTeam": "NDRF Rescue Squad Alpha-2",
                "estimatedArrivalMinutes": 8,
            }
        ]

        # 8. Early Warning Broadcast Alerts
        self.alerts: List[Dict[str, Any]] = [
            {
                "id": "ALT-001",
                "title": "RED ALERT: Impending Slope Failure Sector B",
                "severity": "CRITICAL",
                "source": "Uttarakhand Disaster Management Authority (USDMA)",
                "targetArea": "Joshimath Sector B, Sunil & Manohar Bagh",
                "affectedDistricts": ["Chamoli"],
                "coordinates": [30.5564, 79.5668],
                "issuedAt": "20 min ago",
                "expiresAt": "in 12 hours",
                "description": "Extensometer sensor array logged continuous deformation rate of 5.8mm/hr following subsurface water accumulation.",
                "instructions": "All civilian populations must execute immediate relocation order. Move strictly along verified SafeRoute Corridor A.",
                "active": True,
                "verified": True,
                "sourceAgency": "USDMA / NDRF",
            },
            {
                "id": "ALT-002",
                "title": "ORANGE ADVISORY: Mahananda River Flash Surge",
                "severity": "WARNING",
                "source": "Central Water Commission (CWC)",
                "targetArea": "Siliguri Lower Ghats & Low-Lying Lowlands",
                "affectedDistricts": ["Darjeeling", "Jalpaiguri"],
                "coordinates": [26.7165, 88.3915],
                "issuedAt": "35 min ago",
                "expiresAt": "in 8 hours",
                "description": "Heavy rainfall in Darjeeling hills (110mm in 4h) resulting in water level rise of 1.4m above warning threshold.",
                "instructions": "Avoid approach to river embankments. Move livestock and sensitive household assets to elevated ground.",
                "active": True,
                "verified": True,
                "sourceAgency": "CWC / IMD",
            },
        ]

# Global singleton database instance
db = DisasterDatabase()
